name: Download Linphone Wheel

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: List snapshots
        run: |
          echo "=== 5.4 folder ==="
          curl -s "https://download.linphone.org/snapshots/linphone-python/5.4/" || true
          echo "=== 5.5 folder ==="
          curl -s "https://download.linphone.org/snapshots/linphone-python/5.5/" || true
          echo "=== linphone-python folder ==="
          curl -s "https://download.linphone.org/snapshots/linphone-python/linphone-python/" || true
